services:
  db:
    image: postgres:15-alpine
    container_name: fuss_free_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fussfeed_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: feedback_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fussfeed_db
      - TRIPCODE_SALT=change_me_to_a_secure_random_salt
      - SECRET_KEY=change_me_to_a_secure_random_secret_key
      - API_VERSION=v1
    depends_on:
      - db
    restart: always
    command: >
      sh -c "uv run alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: